CREATE DATABASE IF NOT EXISTS groupbuy DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
USE groupbuy;

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL COMMENT '供货商名称',
    stall_number VARCHAR(50) NOT NULL COMMENT '档口号',
    contact VARCHAR(50) DEFAULT '' COMMENT '联系方式',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_stall (stall_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供货商/档口';

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL COMMENT '商品名称',
    category VARCHAR(50) DEFAULT '' COMMENT '分类',
    unit VARCHAR(20) NOT NULL DEFAULT '份' COMMENT '计量单位',
    price DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '单价',
    supplier_id BIGINT UNSIGNED NOT NULL COMMENT '供货商ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_supplier (supplier_id),
    KEY idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品';

CREATE TABLE IF NOT EXISTS pickup_points (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL COMMENT '提货点名称',
    address VARCHAR(255) DEFAULT '' COMMENT '地址',
    contact VARCHAR(50) DEFAULT '' COMMENT '联系人电话',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提货点';

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(32) NOT NULL COMMENT '订单号',
    product_id BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
    pickup_point_id BIGINT UNSIGNED NOT NULL COMMENT '提货点ID',
    quantity INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '数量',
    unit_price DECIMAL(10,2) NOT NULL COMMENT '下单时单价',
    total_price DECIMAL(10,2) NOT NULL COMMENT '小计金额',
    order_date DATE NOT NULL COMMENT '下单日期',
    customer_name VARCHAR(50) DEFAULT '' COMMENT '买家姓名',
    customer_phone VARCHAR(20) DEFAULT '' COMMENT '买家电话',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1-待分拣 2-已分拣 3-已提货',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_order_date (order_date),
    KEY idx_product (product_id),
    KEY idx_pickup (pickup_point_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单';
